// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route

func init() {
	
	routePathMap["/clan/user/save"] = "internal/model/clan/user.go:27"
	routePathMap["/clan/user/load"] = "internal/model/clan/user.go:54"
	routePathMap["/clan/member/get-by-id"] = "internal/model/clan/member.go:63"
	routePathMap["/clan/member/search-member"] = "internal/model/clan/member.go:101"
	routePathMap["/clan/member/load"] = "internal/model/clan/member.go:123"
	routePathMap["/clan/member/update"] = "internal/model/clan/member.go:145"
	routePathMap["/clan/member/add-child"] = "internal/model/clan/member.go:230"
	routePathMap["/clan/member/delete"] = "internal/model/clan/member.go:307"
}

