// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route

func init() {
	
	routePathMap["/clan/member/get-by-id"] = "internal/model/clan/member.go:46"
	routePathMap["/clan/member/search-member"] = "internal/model/clan/member.go:83"
	routePathMap["/clan/user/save"] = "internal/model/clan/user.go:27"
	routePathMap["/clan/user/load"] = "internal/model/clan/user.go:54"
}

