// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"github.com/google/wire"
	"github.com/tinkler/mqttadmin/pkg/conf"
	"net/http"
)

// Injectors from wire.go:

// NewServer 新建服务
func NewServer() (*http.Server, error) {
	confConf := conf.NewConf()
	server, err := NewRouter(confConf)
	if err != nil {
		return nil, err
	}
	return server, nil
}

// wire.go:

var (
	confSet = wire.NewSet(conf.NewGormConfig, conf.NewConf)
)
