// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: auth/v1/auth.proto

package auth_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthGsrvClient is the client API for AuthGsrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthGsrvClient interface {
	UserManagerAllUser(ctx context.Context, opts ...grpc.CallOption) (AuthGsrv_UserManagerAllUserClient, error)
}

type authGsrvClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthGsrvClient(cc grpc.ClientConnInterface) AuthGsrvClient {
	return &authGsrvClient{cc}
}

func (c *authGsrvClient) UserManagerAllUser(ctx context.Context, opts ...grpc.CallOption) (AuthGsrv_UserManagerAllUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &AuthGsrv_ServiceDesc.Streams[0], "/auth.v1.AuthGsrv/UserManagerAllUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &authGsrvUserManagerAllUserClient{stream}
	return x, nil
}

type AuthGsrv_UserManagerAllUserClient interface {
	Send(*anypb.Any) error
	Recv() (*anypb.Any, error)
	grpc.ClientStream
}

type authGsrvUserManagerAllUserClient struct {
	grpc.ClientStream
}

func (x *authGsrvUserManagerAllUserClient) Send(m *anypb.Any) error {
	return x.ClientStream.SendMsg(m)
}

func (x *authGsrvUserManagerAllUserClient) Recv() (*anypb.Any, error) {
	m := new(anypb.Any)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuthGsrvServer is the server API for AuthGsrv service.
// All implementations must embed UnimplementedAuthGsrvServer
// for forward compatibility
type AuthGsrvServer interface {
	UserManagerAllUser(AuthGsrv_UserManagerAllUserServer) error
	mustEmbedUnimplementedAuthGsrvServer()
}

// UnimplementedAuthGsrvServer must be embedded to have forward compatible implementations.
type UnimplementedAuthGsrvServer struct {
}

func (UnimplementedAuthGsrvServer) UserManagerAllUser(AuthGsrv_UserManagerAllUserServer) error {
	return status.Errorf(codes.Unimplemented, "method UserManagerAllUser not implemented")
}
func (UnimplementedAuthGsrvServer) mustEmbedUnimplementedAuthGsrvServer() {}

// UnsafeAuthGsrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthGsrvServer will
// result in compilation errors.
type UnsafeAuthGsrvServer interface {
	mustEmbedUnimplementedAuthGsrvServer()
}

func RegisterAuthGsrvServer(s grpc.ServiceRegistrar, srv AuthGsrvServer) {
	s.RegisterService(&AuthGsrv_ServiceDesc, srv)
}

func _AuthGsrv_UserManagerAllUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthGsrvServer).UserManagerAllUser(&authGsrvUserManagerAllUserServer{stream})
}

type AuthGsrv_UserManagerAllUserServer interface {
	Send(*anypb.Any) error
	Recv() (*anypb.Any, error)
	grpc.ServerStream
}

type authGsrvUserManagerAllUserServer struct {
	grpc.ServerStream
}

func (x *authGsrvUserManagerAllUserServer) Send(m *anypb.Any) error {
	return x.ServerStream.SendMsg(m)
}

func (x *authGsrvUserManagerAllUserServer) Recv() (*anypb.Any, error) {
	m := new(anypb.Any)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuthGsrv_ServiceDesc is the grpc.ServiceDesc for AuthGsrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthGsrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.AuthGsrv",
	HandlerType: (*AuthGsrvServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UserManagerAllUser",
			Handler:       _AuthGsrv_UserManagerAllUser_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "auth/v1/auth.proto",
}
