name: Clan
description: 中华族谱.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  connectivity_plus: ^4.0.1
  dio: ^5.1.1
  file_picker: ^5.3.1
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.3.8
  fluttertoast: ^8.2.1
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  provider: ^6.0.5
  webview_flutter: ^4.2.1
  webview_flutter_android: ^3.7.1
  webview_flutter_wkwebview: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/