// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route

func init() {
	
	routePathMap["/article/article/save"] = "internal/model/article/article.go:57"
	routePathMap["/article/articles/home-list"] = "internal/model/article/article.go:31"
}

