// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route
import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/tinkler/mqttadmin/pkg/jsonz/sjson"
	"github.com/tinkler/clancloud/backend/article/internal/model/article"
	"github.com/tinkler/mqttadmin/pkg/status"
)

func RoutesArticle(m chi.Router) {
	m.Route("/article", func(r chi.Router) {
		
		r.Post("/article/save", func(w http.ResponseWriter, r *http.Request) {
			m := Model[*article.Article, any]{}
			err := sjson.Bind(r, &m)
			if err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			res := Res[*article.Article,any]{Data:m.Data}
			err = m.Data.Save(r.Context())
			
			if status.HttpError(w, err) {
				return
			}
			if sjson.HttpWrite(w, res) {
				return
			}

		})
		r.Post("/articles/home-list", func(w http.ResponseWriter, r *http.Request) {
			m := Model[*article.Articles, any]{}
			err := sjson.Bind(r, &m)
			if err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			res := Res[*article.Articles,[]*article.Article]{Data:m.Data}
			res.Resp, err = m.Data.HomeList(r.Context())
			
			if status.HttpError(w, err) {
				return
			}
			if sjson.HttpWrite(w, res) {
				return
			}

		})
	})
}
