// Code generated by github.com/tinkler/mqttadmin; DO NOT EDIT.
package route

func init() {
	
	routePathMap["/memorial/memorials/load"] = "internal/model/memorial/memorials.go:20"
	routePathMap["/memorial/memorial/create"] = "internal/model/memorial/memorial.go:39"
	routePathMap["/memorial/memorial/update"] = "internal/model/memorial/memorial.go:96"
	routePathMap["/memorial/memorial/delete"] = "internal/model/memorial/memorial.go:113"
	routePathMap["/memorial/memorial/commemorate"] = "internal/model/memorial/memorial.go:143"
	routePathMap["/memorial/memorial/latest-commemorations"] = "internal/model/memorial/memorial.go:172"
}

